# Generated by Django 5.2.3 on 2025-07-02 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizsubmission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dailysignin',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='socialtasksubmission',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=10),
        ),
        migrations.AlterField(
            model_name='socialtask',
            name='url',
            field=models.URLField(help_text='Link to the task (e.g. Twitter post)'),
        ),
        migrations.AlterField(
            model_name='socialtasksubmission',
            name='proof',
            field=models.URLField(help_text='URL of the proof (e.g. tweet, screenshot, etc.)'),
        ),
        migrations.CreateModel(
            name='MiningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('device_hash', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailysignin',
            name='mining_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mining.miningsession'),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='mining_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mining.miningsession'),
        ),
        migrations.AddField(
            model_name='socialtasksubmission',
            name='mining_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mining.miningsession'),
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='ip_address',
        ),
    ]
