# Generated by Django 5.2.3 on 2025-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_alter_quizsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquiz',
            name='reward',
            field=models.DecimalField(decimal_places=8, default=20.0, max_digits=18),
        ),
    ]
