# Generated by Django 5.2.3 on 2025-07-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0003_dailyquiz_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquiz',
            name='reward',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='reward',
            field=models.DecimalField(decimal_places=8, default=20.0, max_digits=18),
        ),
    ]
