services:
  - type: web
    name: munia-web
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Munia.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Munia.settings
      - key: PYTHON_VERSION
        value: 3.11
