# Generated by Django 5.2.3 on 2025-06-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
