# Generated by Django 5.2.3 on 2025-07-01 08:12

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='used_referral_code',
            field=models.CharField(blank=True, default=core.utils.generate_referral_code, max_length=6, null=True),
        ),
    ]
