# Generated by Django 5.2.3 on 2025-07-01 08:15

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_otp_code_alter_userprofile_used_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default=core.utils.generate_referral_code, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='used_referral_code',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
