# Generated by Django 5.2.3 on 2025-07-05 23:19

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_userprofile_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(default=core.utils.generate_referral_code, max_length=10),
        ),
    ]
