# Generated by Django 5.2.3 on 2025-07-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_topearnerleaderboard_delete_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='topearnerleaderboard',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
