# Generated by Django 5.2.3 on 2025-07-05 11:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_topearnerleaderboard_last_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopEarnerLeaderboard',
            new_name='Leaderboard',
        ),
    ]
