# Generated by Django 5.2.3 on 2025-07-05 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_rename_topearnerleaderboard_leaderboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={},
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='rank',
            new_name='earning_rank',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='referral_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
