# Generated by Django 5.2.3 on 2025-07-05 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_alter_leaderboard_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopEarner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_earner_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_earnings'],
            },
        ),
        migrations.CreateModel(
            name='TopReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_referral_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_referrals'],
            },
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
