# Generated by Django 5.2.3 on 2025-06-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='MUN', max_length=10),
        ),
    ]
