# Generated by Django 5.2.3 on 2025-07-02 20:32

import django.db.models.deletion
import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_id_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_wallet',
            field=models.ForeignKey(default=wallet.models.get_admin_wallet, on_delete=django.db.models.deletion.CASCADE, related_name='related_transactions', to='wallet.wallet'),
        ),
    ]
