"""
Django settings for Munia project.
Generated by 'django-admin startproject' using Django 5.2.3.
Docs:
- Settings: https://docs.djangoproject.com/en/5.2/ref/settings/
- Deployment: https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
"""

from pathlib import Path
from datetime import timedelta
import os
import certifi
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Munia.settings')
application = get_wsgi_application()

os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()
os.environ['SSL_CERT_FILE'] = certifi.where()


# --------------------------------------
# Base Directory
# --------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------
# Core Settings
# --------------------------------------
# --------------------------------------
# Core Settings
# --------------------------------------
# --------------------------------------
# Core Settings
# --------------------------------------
# --------------------------------------
# Core Settings
# --------------------------------------
SECRET_KEY = os.getenv("SECRET_KEY", "fallback")
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = ['.onrender.com', '127.0.0.1']



# --------------------------------------
# Installed Applications
# --------------------------------------
INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',

    # Project apps
    'core',
    'wallet',
    'audit',
    'kyc',
    'mining',
    'leaderboard',
    'referral',
    'support',
]

# --------------------------------------
# Middleware
# --------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

# --------------------------------------
# URLs and WSGI
# --------------------------------------
ROOT_URLCONF = 'Munia.urls'
WSGI_APPLICATION = 'Munia.wsgi.application'


# --------------------------------------
# Templates
# --------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# --------------------------------------
# Database
# --------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'munia_database_jp2g',
        'USER': 'munia_database_jp2g_user',
        'PASSWORD': 'kbeJo4JUKv1Fw8XsGCj68y0HQPb2If61',
        'HOST': 'dpg-d1gk6nemcj7s73cst630-a.oregon-postgres.render.com',
        'PORT': '5432',
    }
}

# --------------------------------------
# Custom User Model
# --------------------------------------
AUTH_USER_MODEL = 'core.User'

# --------------------------------------
# Password Validation
# --------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------------------
# Internationalization
# --------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --------------------------------------
# Static Files
# --------------------------------------
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = 'static/'

# --------------------------------------
# Default Auto Field
# --------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------
# REST Framework
# --------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# --------------------------------------
# JWT Settings
# --------------------------------------
SIMPLE_JWT = {
    'BLACKLIST_AFTER_ROTATION': True,
    'ROTATE_REFRESH_TOKENS': True,
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=72),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# --------------------------------------
# CORS (Cross-Origin Resource Sharing)
# --------------------------------------
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "https://v0-send-and-receive-page.vercel.app",
]

# --------------------------------------
# Email Settings
# --------------------------------------
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
SENDGRID_SANDBOX_MODE_IN_DEBUG = False 
SENDGRID_ECHO_TO_STDOUT = False  
DEFAULT_FROM_EMAIL = "muniaofficials@gmail.com"
 
# Security headers
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
